# Default configuration for RL training

# MDP configuration
mdp:
  lookback_window: 100
  prediction_horizon: 1
  use_proprietary_features: true
  risk_free_rate: 0.02
  transaction_cost: 0.001
  max_position: 1.0
  cvar_alpha: 0.05
  risk_tolerance: 0.1

# Training configuration
trainer:
  initial_train_window: 2880000  # 2 years in minutes
  validation_window: 259200      # 6 months in minutes
  step_size: 43200              # 1 month in minutes
  retrain_frequency: rolling     # rolling or expanding
  batch_size: 256
  replay_buffer_size: 1000000
  learning_starts: 10000
  update_frequency: 1
  gradient_steps: 1
  min_train_size: 1000000

# General training
num_epochs: 3

# SAC configuration
sac_config:
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  automatic_entropy_tuning: true
  hidden_dims: [512, 512, 256]
  learning_rate: 0.0003

# PPO configuration
ppo_config:
  gamma: 0.99
  gae_lambda: 0.95
  clip_epsilon: 0.2
  value_loss_coef: 0.5
  entropy_coef: 0.01
  learning_rate: 0.0003
  hidden_dims: [512, 512, 256]
  n_steps: 2048
  n_epochs: 10

# DDPG configuration
ddpg_config:
  gamma: 0.99
  tau: 0.005
  noise_std: 0.1
  noise_clip: 0.5
  hidden_dims: [512, 512, 256]
  learning_rate: 0.0003

# TD3 configuration
td3_config:
  gamma: 0.99
  tau: 0.005
  noise_std: 0.2
  noise_clip: 0.5
  policy_delay: 2
  hidden_dims: [512, 512, 256]
  learning_rate: 0.0003

# TD-MPC2 configuration
td_mpc2_config:
  gamma: 0.99
  tau: 0.005
  horizon: 5
  hidden_dims: [512, 512, 256]
  latent_dim: 256
  learning_rate: 0.0003
  beta: 0.1  # Policy constraint coefficient

# Ensemble configuration
ensemble_config:
  base_agents:
    sac:
      enabled: true
      gamma: 0.99
      tau: 0.005
      alpha: 0.2
      hidden_dims: [256, 256]
    ppo:
      enabled: true
      gamma: 0.99
      hidden_dims: [256, 256]
    ddpg:
      enabled: true
      gamma: 0.99
      tau: 0.005
      hidden_dims: [256, 256]
    td3:
      enabled: true
      gamma: 0.99
      tau: 0.005
      hidden_dims: [256, 256]
    td_mpc2:
      enabled: true
      gamma: 0.99
      horizon: 3
      hidden_dims: [256, 256]
  
  meta_agent_config:
    gamma: 0.99
    tau: 0.005
    alpha: 0.2
    hidden_dims: [512, 512]
  
  meta_hidden_dims: [256, 256]
  meta_learning_rate: 0.0001
  train_base_agents: true
  train_meta_agent: true
  use_weighted_combination: true
  blend_factor: 0.7
